name: Pipeline de teste da API

on:
  push:
    branches: [main]

jobs:
  teste-unitarios:
    runs-on: ubuntu-latest
    env:
      END_POINT_V1: "/api/v1"
      PORT: 3333
    steps:
      - name: Checkout projeto
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependecies
        run: npm install

      - name: Subir API
        run: node src/server.js

      - name: Iniciar testes
        run: npm test
