name: Pipeline de teste da API

on:
  push:
    branches: [main]

jobs:
  teste-unitarios:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout projeto
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependecies
        run: npm install

      - name: Subir API
        run: npm run start

      - name: Iniciar testes
        run: npm test
